src/Entity/Property.php
<?php
namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="guid")
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $county;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $town;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=65535)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $displayable_address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thumbnail;

    /**
     * @ORM\Column(type="integer")
     */
    private $no_bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $no_bathrooms;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $property_type;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $lonitude;

//    /**
//     * @ORM\Column(type="string", nullable=true)
//     */
//    private $fullDetailsUrl;

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function getCounty(): ?string
    {
        return $this->county;
    }

    public function setCounty(string $county): self
    {
        $this->county = $county;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): self
    {
        $this->town = $town;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDisplayableAddress(): ?string
    {
        return $this->displayable_address;
    }

    public function setDisplayableAddress(string $displayable_address): self
    {
        $this->displayable_address = $displayable_address;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getNoBedrooms(): ?int
    {
        return $this->no_bedrooms;
    }

    public function setNoBedrooms(int $no_bedrooms): self
    {
        $this->no_bedrooms = $no_bedrooms;

        return $this;
    }

    public function getNoBathrooms(): ?int
    {
        return $this->no_bathrooms;
    }

    public function setNoBathrooms(int $no_bathrooms): self
    {
        $this->no_bathrooms = $no_bathrooms;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPropertyType(): ?string
    {
        return $this->property_type;
    }

    public function setPropertyType(string $property_type): self
    {
        $this->property_type = $property_type;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function setUuid(string $uuid): void
    {
        $this->uuid = $uuid;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): void
    {
        $this->latitude = $latitude;
    }

    public function getLonitude(): ?string
    {
        return $this->lonitude;
    }

    public function setLonitude(string $lonitude): void
    {
        $this->lonitude = $lonitude;
    }

//    The task specifies full detail url but i do not know what this applies to. the sample DB doesnt contain full details url to map here
//    public function getFullDetailsUrl(): ?string
//    {
//        return $this->fullDetailsUrl;
//    }
//
//    public function setFullDetailsUrl(string $fullDetailsUrl): void
//    {
//        $this->fullDetailsUrl = $fullDetailsUrl;
//    }
}

src/Form/PropertyType.php
<?php
namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('uuid', HiddenType::class)
            ->add('county')
            ->add('country', CountryType::class)
            ->add('town')
            ->add('postcode')
            ->add('description', TextareaType::class)
            ->add('displayable_address')
            ->add('image', FileType::class, [
                'label' => 'Image (JPEG file)',
                // unmapped means that this field is not associated to any entity property
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid JPEG image',
                    ]),
                ],
            ])
            ->add('no_bedrooms', ChoiceType::class, self::NUMBERSMAP)
            ->add('no_bathrooms', ChoiceType::class, self::NUMBERSMAP)
            ->add('price', IntegerType::class)
            ->add('property_type', ChoiceType::class, self::PROPERTYTYPESMAP)
            ->add('type', ChoiceType::class, self::RADIOCHOICES);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }

    public const PROPERTYTYPESMAP = [
        'choices' => [
            'Flat' => 1,
            'Detached' => 2,
            'Semi-detached' => 3,
            'Terraced' => 4,
            'End of Terrace' => 5,
            'Cottage' => 6,
            'Bungalow' => 7,
        ],
    ];

    public const RADIOCHOICES = [
        'multiple' => false,
        'expanded' => true,
        'choices' => [
            'rent' => 'rent',
            'sale' => 'sale',
        ],
    ];

    public const NUMBERSMAP = [
        'choices' => [
            1 => '1',
            2 => '2',
            3 => '3',
            4 => '4',
            5 => '5',
            6 => '6',
            7 => '7',
            8 => '8',
            9 => '9',
            10 => '10',
            11 => '11',
            12 => '12',
            13 => '13',
            14 => '14',
            15 => '15',
        ],
    ];
}

src/Controller/Admin/PropertyController.php
<?php
namespace App\Controller\Admin;

use App\Controller\BaseController;
use App\Entity\Property;
use App\Form\PropertyType;
use App\Form\SearchPropertyType;
use App\Repository\PropertyRepository;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;

class PropertyController extends BaseController
{
    /**
     * @Route("/", name="property_index", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('property/index.html.twig', [
            'property' => $propertyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="property_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();

            // this condition is needed because the 'image' field is not required
            if ($imageFile) {
                $imageFileName = $fileUploader->upload($imageFile);
                $property->setImage($imageFileName);
            }

            $property->setUuid(Uuid::v6());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('property_index');
        }

        return $this->render('property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{uuid}", name="property_show", methods={"GET"}, requirements={"uuid"="%regex.uuid%"})
     */
    public function show(Property $property): Response
    {
        return $this->render('property/show.html.twig', [
            'property' => $property,
        ]);
    }

    /**
     * @Route("/search", name="property_search", methods={"GET","POST"})
     */
    public function search(Request $request, PropertyRepository $repository): Response
    {
        $form = $this->createForm(SearchPropertyType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $repository->searchPropertiesByValues($form->getData());

            return $this->render('property/index.html.twig', [
                'property' => $data, // this should be array of properties matching the expected
            ]);
        }

        return $this->render('property/search.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{uuid}/edit", name="property_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();

            // this condition is needed because the 'image' field is not required
            if ($imageFile) {
                $imageFileName = $fileUploader->upload($imageFile);
                $property->setImage($imageFileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('property_index');
        }

        return $this->render('property/edit.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{uuid}", name="property_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Property $property): Response
    {
        if ($this->isCsrfTokenValid('delete' . $property->getUuid(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($property);
            $entityManager->flush();
        }

        return $this->redirectToRoute('property_index');
    }
}

templates/property/_delete_form.html.twig
<form method="post" action="{{ path('property_delete', {'uuid': property.uuid}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.uuid) }}">
    <button class="btn">Delete</button>
</form>

templates/property/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Property{% endblock %}

{% block body %}
    <h1>Edit Property</h1>

    {{ include('property/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('property_index') }}">back to list</a>

    {{ include('property/_delete_form.html.twig') }}
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property index{% endblock %}

{% block body %}

    <h1>Property index</h1>
    <a href="{{ path('property_search') }}">Search</a>

    <a href="{{ path('property_new') }}">Create new</a>
    <table class="table">
        <thead>
        <tr>
            <th>Uuid</th>
            <th>County</th>
            <th>Country</th>
            <th>Town</th>
            <th>Postcode</th>
            <th>Description</th>
            <th>Displayable_address</th>
            <th>Image</th>
            <th>Thumbnail</th>
            <th>No_bedrooms</th>
            <th>No_bathrooms</th>
            <th>Price</th>
            <th>Property_type</th>
            <th>Type</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for property in property %}
            <tr>
                <td>{{ property.uuid }}</td>
                <td>{{ property.county }}</td>
                <td>{{ property.country }}</td>
                <td>{{ property.town }}</td>
                <td>{{ property.postcode }}</td>
                <td>{{ property.description }}</td>
                <td>{{ property.displayableAddress }}</td>
                <td>{{ property.image }}</td>
                <td>{{ property.thumbnail }}</td>
                <td>{{ property.noBedrooms }}</td>
                <td>{{ property.noBathrooms }}</td>
                <td>{{ property.price }}</td>
                <td>{{ property.propertyType }}</td>
                <td>{{ property.type }}</td>
                <td>
                    <a href="{{ path('property_show', {'uuid': property.uuid}) }}">show</a>
                    <a href="{{ path('property_edit', {'uuid': property.uuid}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found (OMG!)</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('property_new') }}">Create new</a>
{% endblock %}

templates/property/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Property{% endblock %}

{% block body %}
    <h1>Create new Property</h1>

    {{ include('property/_form.html.twig') }}

    <a href="{{ path('property_index') }}">back to list</a>
{% endblock %}

templates/property/search.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}Property search{% endblock %}#}

{#{% block body %}#}
{#    <h1>Property index</h1>#}


{#{% endblock %}#}

{#{{ form_start(form) }}#}

{#<div>#}
{#    {{ form_widget(form.county) }}#}
{#    {{ form_errors(form.county) }}#}
{#</div>#}

{# Render CSRF token etc .#}
{#<div style="display:none">#}
{#    {{ form_rest(form) }}#}
{#</div>#}

{#<input type="submit" value="Submit">#}

{#{{ form_end(form) }}#}
{% extends 'base.html.twig' %}

{% block title %}Search for Property{% endblock %}

{% block body %}
    <h1>Search Property</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('GO!') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('property_index') }}">back to list</a>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property{% endblock %}

{% block body %}
    <h1>Property</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Uuid</th>
                <td>{{ property.uuid }}</td>
            </tr>
            <tr>
                <th>County</th>
                <td>{{ property.county }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ property.country }}</td>
            </tr>
            <tr>
                <th>Town</th>
                <td>{{ property.town }}</td>
            </tr>
            <tr>
                <th>Postcode</th>
                <td>{{ property.postcode }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ property.description }}</td>
            </tr>
            <tr>
                <th>Displayable_address</th>
                <td>{{ property.displayableAddress }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>
                    <img src="{{ asset(('/media/'~ property.image))|imagine_filter('avatar') }}"/>
                    </td>
            </tr>
            <tr>
                <th>No_bedrooms</th>
                <td>{{ property.noBedrooms }}</td>
            </tr>
            <tr>
                <th>No_bathrooms</th>
                <td>{{ property.noBathrooms }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ property.price }}</td>
            </tr>
            <tr>
                <th>Property_type</th>
                <td>{{ property.propertyType }}</td>
            </tr>
            <tr>
                <th>For_sale</th>
                <td>{{ property.forSale ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>For_rent</th>
                <td>{{ property.forRent ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('property_index') }}">back to list</a>

    <a href="{{ path('property_edit', {'uuid': property.uuid}) }}">edit</a>

    {{ include('property/_delete_form.html.twig') }}
{% endblock %}